#!/usr/bin/env python3
"""Generate Saki's LVGL GB2312 fallback font from Noto Sans CJK SC."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path

LV_FONT_CONV_VERSION = "1.5.3"
NOTO_FONT_SHA256 = "2c76254f6fc379fddfce0a7e84fb5385bb135d3e399294f6eeb6680d0365b74b"


def gb2312_symbols() -> str:
    """Return every Unicode character addressable by the GB2312 code page."""
    symbols: list[str] = []
    seen: set[str] = set()
    for lead in range(0xA1, 0xF8):
        for trail in range(0xA1, 0xFF):
            try:
                character = bytes((lead, trail)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if character not in seen:
                seen.add(character)
                symbols.append(character)

    # Keep an explicit missing-glyph marker even if a future codec table changes.
    if "□" not in seen:
        symbols.append("□")
    return "".join(symbols)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, type=Path, help="NotoSansCJKsc-Regular.otf")
    parser.add_argument("--output", required=True, type=Path, help="generated LVGL C file")
    args = parser.parse_args()

    if not args.font.is_file():
        parser.error(f"font does not exist: {args.font}")
    digest = hashlib.sha256(args.font.read_bytes()).hexdigest()
    if digest != NOTO_FONT_SHA256:
        parser.error(f"unexpected Noto font SHA-256: {digest}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.unlink(missing_ok=True)

    command = [
        "npx",
        "--yes",
        f"lv_font_conv@{LV_FONT_CONV_VERSION}",
        "--size",
        "16",
        "--bpp",
        "2",
        "--format",
        "lvgl",
        "--font",
        str(args.font),
        "--symbols",
        gb2312_symbols(),
        "--autohint-strong",
        "--no-kerning",
        "--lv-include",
        "lvgl.h",
        "--lv-font-name",
        "saki_font_cjk_16",
        "--output",
        str(args.output),
    ]
    subprocess.run(command, check=True)

    generated = args.output.read_text(encoding="utf-8")
    comment_end = generated.find("*/")
    if comment_end < 0:
        raise RuntimeError("lv_font_conv output is missing its metadata header")
    generated = generated[comment_end + 2 :].lstrip()
    header = f"""/*******************************************************************************
 * Generated by scripts/generate_cjk_font.py; do not edit manually.
 * Source: NotoSansCJKsc-Regular.otf
 * Source SHA-256: {NOTO_FONT_SHA256}
 * Coverage: 7,445 GB2312 symbols, 16 px, 2 bpp, compressed.
 * License: SIL Open Font License 1.1 (see fonts/licenses/).
 *******************************************************************************/

"""
    args.output.write_text(header + generated.rstrip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
